apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esgf-wget.fullname" . }}-secret
  labels:
    {{- include "esgf-wget.labels" . | nindent 4 }}
type: Opaque
data:
  ESGF_WGET_SECRET_KEY: {{ .Values.wgetApi.secretKey | default (randAlphaNum 32) | b64enc }}
  GLOBUS_CLI_CLIENT_ID: {{ required "A valid .Values.wgetApi.globusClientId is required!" .Values.wgetApi.globusClientId | b64enc }}
  GLOBUS_CLI_CLIENT_SECRET: {{ required "A valid .Values.wgetApi.globusClientSecret is required!" .Values.wgetApi.globusClientSecret | b64enc }}
