name: Build and Push Container

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docekr meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: esgf/esgf-wget
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}