name: Release Helm Chart

on:
  push:
    tags:
      - '[0-9]+.[0-9]+**'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Lint chart
        run: helm lint chart/esgf-wget
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_OWNER: "ESGF"
          CR_GIT_REPO: "esgf-wget"
          CR_PACKAGE_PATH: chart/esgf-wget
          CR_SKIP_EXISTING: true
